### PR TITLE
don't include Frameworks into DTTableViewManager.framework

### PR DESCRIPTION
**Pull request by etataurov**
Otherwise iTunes Connect rejects app that embeds DTTableViewManager.framework
```
[18:46:06]: ERROR ITMS-90206: "Invalid Bundle. The bundle at 'MyApp.app/Frameworks/DTModelStorage.framework' contains disallowed file 'Frameworks'."
```
I'm using Carthage, but seems like CocoaPods might complain about EMBEDDED_CONTENT_CONTAINS_SWIFT = NO;
There is an ongoing discussion in CocoaPods https://github.com/CocoaPods/CocoaPods/issues/4515

### CODE REVIEW

**Comment by DenHeadless** [comment]
Yep, it seems like Apple knows about this stuff.
https://developer.apple.com/library/ios/qa/qa1881/_index.html

Thanks, @etataurov!

**Comment by DenHeadless** [comment]
I removed this build setting from all three repos, DTTableViewManager, DTModelStorage and DTCollectionViewManager. Can you try building from master branch and tell me if submission worked?

**Comment by etataurov** [comment]
@DenHeadless Thanks a lot!
Also I've forgotten tvOS in my PR, but seems you've made it

I'll try it

**Comment by etataurov** [comment]
I've only tried DTTableViewManager's master branch, but DTModelStorage was 2.3.0, because there is strict version in DTTableViewManager's Cartfile

unfortunately  DTTableViewManager.framework in my Carthage/Build/iOS still contains Frameworks directory. Even after clean.
But when I build DTTableViewManager myself using Xcode, DTTableViewManager.framework in DerivedData does not contain it

Is DTModelStorage 2.3.0 a cause of it?

**Comment by DenHeadless** [comment]
It might. Please try building from master again, i added 2.3.1 tag to DTModelStorage, and refer to it in Cartfile.

**Comment by etataurov** [comment]
Oh, actually it worked, after I removed ModuleCache. My fault.

DTModelStorage from master branch doesn't contain Frameworks dir in *.framework.
(iTunes Connect rejects build with Frameworks dir in *.framework. So it possible just to delete this dir and build will be accepted, that worked for me yesterday. So absence of Frameworks dir means that build is OK)

So everything is fine. Thank you!
But I've only tested DTTableViewManager and DTModelStorage for iOS

**Comment by etataurov** [comment]
Build with DTTableViewManager from master & DTModelStorage = 2.3.1 was accepted by iTunes Connect
Thanks again!

**Comment by DenHeadless** [comment]
No problem! :beers:

**Comment by DenHeadless** [comment]
Aaaand now DTTableViewManager and DTCollectionViewManager tests are failing, because apparently DTModelStorage **has** to have this setting turned on. Oh Apple, you are making me sad.

I will probably need to reconfigure all CI setup because of this.

Possibly related links:

https://github.com/CocoaPods/CocoaPods/issues/2894
https://twitter.com/jamayers/status/582997970477400066
http://stackoverflow.com/questions/25777958/validation-error-invalid-bundle-the-bundle-at-contains-disallowed-file-fr

**Pull request merged**
